# Generated by Django 5.0.2 on 2024-03-07 10:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Priority",
            fields=[
                ("PriorityID", models.IntegerField(primary_key=True, serialize=False)),
                ("PriorityName", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("StatusID", models.AutoField(primary_key=True, serialize=False)),
                ("Status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("UserID", models.AutoField(primary_key=True, serialize=False)),
                ("UserName", models.CharField(max_length=20, unique=True)),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("Password", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="TaskInformation",
            fields=[
                ("TaskID", models.IntegerField(primary_key=True, serialize=False)),
                ("Title", models.CharField(max_length=100)),
                ("Description", models.TextField()),
                ("StartDate", models.DateTimeField(auto_now_add=True)),
                ("DueDate", models.DateField()),
                (
                    "PriorityID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Management.priority",
                    ),
                ),
                (
                    "Status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Management.status",
                    ),
                ),
                (
                    "Assignedby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Management.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskData",
            fields=[
                ("AssignedID", models.IntegerField(primary_key=True, serialize=False)),
                ("DueDate", models.DateField()),
                (
                    "PriorityID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Management.priority",
                    ),
                ),
                (
                    "Status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Management.status",
                    ),
                ),
                (
                    "TaskID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Management.taskinformation",
                    ),
                ),
                (
                    "AssignedTo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Assigned", to="Management.users"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                ("CommentID", models.AutoField(primary_key=True, serialize=False)),
                ("Content", models.TextField()),
                ("Date", models.DateTimeField(auto_now_add=True)),
                (
                    "TaskID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Management.taskinformation",
                    ),
                ),
                (
                    "UserID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Management.users",
                    ),
                ),
            ],
        ),
    ]
