# File: azure-pipelines.yml

trigger:
- main  # Branch to trigger pipeline on

pool:
  vmImage: 'ubuntu-latest'  # Specify the agent pool and image

variables:
  # Define variables such as the Python version and other environment configurations
  python.version: '3.x'

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: Build
    displayName: 'Build job'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        addToPath: true

    - script: |
        python manage.py collectstatic --noinput
      displayName: 'Collect static files'

    # Add more build steps as needed, such as running migrations, etc.

